# Generated by Django 3.0.8 on 2020-08-03 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_bids_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imgURL', models.URLField(blank=True)),
                ('category', models.CharField(blank=True, choices=[('Home', 'Home'), ('Mens Fashion', 'Mens Fashion'), ('Womens Fashion', 'Womens Fashion'), ('Sports', 'Sports'), ('Electronics', 'Electronics'), ('Grocery', 'Grocery'), ('Others', 'Others')], max_length=20)),
                ('addedTime', models.DateField(auto_now_add=True, verbose_name='date added')),
                ('ended', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Auction',
        ),
    ]
